### ISSUE TITLE
rbl.megarbl.net always return FOUND 

### ISSUE THREAD

**Issue by ghost** [rozie/mail-rbl-monitor#1]
Hi.
Thank you for your RBL app.
1) rbl.megarbl.net always return "FOUND".

2) Is there a possibility you add more reliable RBL's sources to the list?

Thank you,
Sam

**Comment by rozie** [comment]
Hi,
rblcheck.py is rather a tool, and rbls.list is rather a config, so if there is a problem with RBL just remove it from the list. I'd don't use it actively anymore, so need to rely on feedback.

So thank you for your feedback.
1. Will remove it from the list.
2. Any suggestions? PRs are welcome.

Thanks,
rozie

**Comment by rozie** [comment]
After closer look: rbl.megarbl.net is not in the list.

Feel free to make PR with more reliable IPs.

Thanks,
rozie
